language: python
python:
- '3.8'
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: N99er+J6vK4BYgdM4/TSJ3eDNZhefdYIgj76W1ZFXLKmYTW9typTwFd0gbJeZ2VqM8Wu0goSb7ldKaWj1sMZlvnbiwcMshpAU6MzEd04abqJ/uvOS0WEWEezQAGqx+pH02Xlw7MSnD9+HquQonL2Z6qynN9lsEqptD2HyqEB69bZK9ZJRGy+ox4m/dsx0zXcqzrOauV5bSFSa3dnuJFkCCdK9PUS4aqQWv8PdLMOls431LROFtWfu7eMEHkW3pq+VQLZVpx1ebmvpXRlWqJVRQMhNsBVrEIY3eqtLHe/fD9DlHQ2ZAMUWh2QobwuU74Ts6S4dXL6L5voLesiAj4rOstTyVSG1ZG2sbVsYMSB7z7827eAdczOszYnF8bxkVhCvVCuViZRHUNMfIXPmsvOqXRq0HLVEIEiivU9iE6HLoo5W5Garq/9ST5ShlptmI5r9r+RyV6mngW5b9vguZW/Q4CqNoRs2qsXaldGn0xpfFnhsN2uBFTj6WTqRYxgZ+5XB9BxDr/aR2S+sYmRj5s5xpTraGRfxsPqx03TusLYm2/Ohl7+nSByuMRDxna2tag8H37Dsv9rJZwtKCH8GmNHDwLsaLrWHM7+w7jrw5cb6wJX8Se/oHZuOgUdLIp9djvQO1rx+lZiC6ThbNztYHnccFlk6LQXmnLD0CtJJjNJ5H0=
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
