language: python
python:
- '3.8'
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: flVtIVAab0LyC+KaPq8f0sMi9pBnbvDhWJYytyOn7J2239mr5/X9ymvuXUGjHHVhdm3WqBU5zK0WvMD2bX8eps45UtCrnxv4QSDisxOQIeIa7XNmfObSUhBh7xVhUF095B471JJchr6rbb4kTFoq3yhBB8mfur4m4NCjEyX3GRkmKij3xAy++QdD9TvYusq8ccSl8dh5Ywe+J8q6ksssrOiNaI+5Or1rKxiQ+Wdrfq9lOcL8/kNg6vCeENDTjmm/GSQfSvjdTbAWUlQ9dLznnBrBtx23ib1pciPyqZZFXsqRlCKe2tY9o0Wr163AtrIXzXXuNP2WFNxTyMcyTiYBwE6S2byhWuqXsH/9UWMlUw5Cvja/lmK/xhmxXcNTUWqtFJK9OtjIQziJ+1vfm6o3Ef75nL13Iaz6ffe85tnGXMULRZyo5q4puRbFaT9Vo+H7LzanRF4YW+xAX3EargrgrxQ5VOstzticFjRSP3SzFKZm7pZexBGDp77DFXtMN3ngKhoNeW3x46D3aKNZMJM+DfyB3h+aIHnUBtNT1tfxhvdrL0MfCWnst6/mHsFVAxCH6pSBNiKvNMqjYxnMF6/juP/Cc86ifTHe4FHTHBy4/CsmqnAZ9xV/t5XMGYisgVSdg49Xu8SvOrjCLX/Kr6JinxXquW9sCgsph5qmVpjFiiE=
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
