language: python
python:
- '3.8'
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: MSEdzeYbSEppLiBmZa2LyBehdVVY2X/vAAumgK345mcGJZZHsCqKhLd32t1CSZBv08jfwQHkDMq07aBze+37d4VV++zknVGUMo5+mqoLAMtqPbb1J2bY5J9Ca0lOCVG098djJeAaPQVqn8DjfAIk7e82sWZS5uHsbVgw7XGyKeUGGl8GnQCMEwfdJxMI2k07L+kTKyMANrOfw9yyR8Tg84ua/VGzEgJWMHV79UBBQzRR60J6nAW+n7qIGzhN8gNnHCrGU3fMOSZ9zaeQlntNmmxBB79aq5MeUP70VJgE7Ok9RSxGTSV/Z12rVn7OPyd6mflfsXWPiKDC3n9gY3NqVzewMKXvS5eNZeKluwXJPYmVnMpv5/v1DEMCFn5No86G8h2eMuiu6OqhBRyPgO5ZodD+PcOVARnGB/HQu1K4xP4NY1halkHvIt5JIZ2x/gN6fEZI6Oa8eBhMlpdgBBQCNp3V7bepTilZ1pzeiebt8oZjsTr8GogCpgp4y9uzj0nu5BWy34r48GtzEmjvXCU0SUDwyFmkDrXwqrd86VlVvQpG2Gakbaco+A2GVQWEzeeA9JClC2YSZOZ3/+JTl/CNp2Ng25zob/kSkdTRFV7rJ5gFxTn8pNHFi2AvfpAmRYUiXCzI3LsEM0v/TpPtIFqVgW4Kgxzd7q5lBx2w3T0fuvc=
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
